In [1]:
import numpy as np
import pandas as pd

In [2]:
## Creating Series
labels=["a","b","c"]
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [7]:
## Dataframe

In [9]:
## Creating a dataframe
data={
    "Name":["John","Anna","Peter","Linda"],
    "Age":[28,34,29,42],
    "City":["Newyork","Paris","Berlin","London"],
    "Salary":[65000,70000,62000,85000]
}
df=pd.DataFrame(data)

In [12]:
data_list=[
    ["John",28,"New York",65000],
    ["Anna",34,"Paris",70000],
    ["Peter",29,"Berlin",62000],
    ["Linda",42,"London",85000]
]
df2=pd.DataFrame(data_list)
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
## Selection and Indexing of Columns
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [15]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [16]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [18]:
## Creating a new column
df2["Designation"]=["Doctor","Engr","Doctor","Engr"]

In [19]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Engr
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Engr

In [21]:
## Removing Columns
df2.drop("Designation",axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Engr
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Engr

In [23]:
df2.drop("Designation",axis=1,inplace=True)

In [24]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [26]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [27]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [29]:
## Selecting rows
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [30]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [31]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [33]:
## Selecting Subsets of Rows and Columns
df.loc[[0,1]][["City","Salary"]]

      City  Salary
0  Newyork   65000
1    Paris   70000

In [34]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [36]:
## Conditional Statements

df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
## we only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [38]:
## we only want to see those people whose age is above 30 and city must be paris

df2[df2["Age"] > 30 & df2["City"] == "Paris"]

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]

In [39]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000