### **Pandas Dataframe-Creation and Inspection**

In [2]:
import pandas as pd

In [3]:
# Dataframe creation

data={
    "Name":["Ali","Ahmed","Sara"],
    "Age":[18,19,20],
    "Code":["AL","AH","SA"]
}

data_01=pd.DataFrame(data)

In [4]:
data_01

    Name  Age Code
0    Ali   18   AL
1  Ahmed   19   AH
2   Sara   20   SA

In [6]:
# Importing Dataframe
data_02=pd.read_csv('retail_sales.csv')
data_02

            Date     Category        Sales  Quantity      Profit Region
0       1/1/2023  Electronics  1149.014246      11.0  383.664245  North
1       1/1/2023     Clothing   958.520710       7.0  224.054049   East
2       1/1/2023   Home Goods  1473.763845       2.0  466.593090  South
3       1/1/2023       Sports  1230.230419       6.0  123.310460   West
4       1/1/2023         NaN?   828.585950      12.0   88.591355   East
...          ...          ...          ...       ...         ...    ...
1820  12/31/2023  Electronics  1132.749004      14.0  353.464221   West
1821  12/31/2023     Clothing   679.261971       8.0  183.860200  North
1822  12/31/2023   Home Goods  1193.733728      10.0  359.010938  South
1823  12/31/2023       Sports  1076.118706      17.0  259.570916  North
1824  12/31/2023        Books   703.973443      14.0  134.106006   East

[1825 rows x 6 columns]

In [7]:
data_02.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: float64(3), object(3)
memory usage: 85.7+ KB

In [8]:
data_02.describe()

             Sales     Quantity       Profit
count  1823.000000  1820.000000  1825.000000
mean    980.482677    10.053846   248.696130
std     336.756618     5.515370   118.159627
min       0.000000     0.000000     0.000000
25%     784.071354     5.000000   156.916498
50%     997.725134    10.000000   229.344557
75%    1208.512721    15.000000   324.867847
max    1888.932537    19.000000   703.228418

In [9]:
data_02.index

RangeIndex(start=0, stop=1825, step=1)

In [10]:
data_02.value_counts

<bound method DataFrame.value_counts of             Date     Category        Sales  Quantity      Profit Region
0       1/1/2023  Electronics  1149.014246      11.0  383.664245  North
1       1/1/2023     Clothing   958.520710       7.0  224.054049   East
2       1/1/2023   Home Goods  1473.763845       2.0  466.593090  South
3       1/1/2023       Sports  1230.230419       6.0  123.310460   West
4       1/1/2023         NaN?   828.585950      12.0   88.591355   East
...          ...          ...          ...       ...         ...    ...
1820  12/31/2023  Electronics  1132.749004      14.0  353.464221   West
1821  12/31/2023     Clothing   679.261971       8.0  183.860200  North
1822  12/31/2023   Home Goods  1193.733728      10.0  359.010938  South
1823  12/31/2023       Sports  1076.118706      17.0  259.570916  North
1824  12/31/2023        Books   703.973443      14.0  134.106006   East

[1825 rows x 6 columns]>

In [11]:
data_02.dtypes

Date         object
Category     object
Sales       float64
Quantity    float64
Profit      float64
Region       object
dtype: object

In [12]:
data_02.columns

Index(['Date', 'Category', 'Sales', 'Quantity', 'Profit', 'Region'], dtype='object')

In [13]:
data_02.

AttributeError: 'DataFrame' object has no attribute 'rows'