In [2]:
import pandas as pd

In [3]:
i="8"
i

'8'

In [4]:
data_01={
    "Name":["Ali","Ahmed","Ayesha","Farhan"],
    "Age":[34,45,28,8],
    "Salary":[45000,25000,19000,67000],
    
}
data_02=pd.DataFrame(data_01)
data_02

     Name  Age  Salary
0     Ali   34   45000
1   Ahmed   45   25000
2  Ayesha   28   19000
3  Farhan    8   67000

In [5]:
# using loc function

data=data_02.loc[0:1,["Name","Age"]]
data

    Name  Age
0    Ali   34
1  Ahmed   45

In [7]:
# using iloc function

data=data_02.iloc[0:3,0:4]
data

     Name  Age  Salary
0     Ali   34   45000
1   Ahmed   45   25000
2  Ayesha   28   19000

In [9]:
# Boolean Filtering
data=data_02[data_02["Salary"]>20000]
data

     Name  Age  Salary
0     Ali   34   45000
1   Ahmed   45   25000
3  Farhan    8   67000

In [10]:
# Safe Assignment Using loc

data=data_02.loc[data_02["Age"]<20,"Salary"]=50000
data

50000